server:
  port: ${PORT:8761}
spring:
  profiles:
    active: development
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: development
  cloud:
    config:
      uri: http://localhost:8888
---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://${DOCKER_IP:192.168.99.100}:8888
