server:
  port: ${PORT:8100}

security:
  oauth2:
    client:
      clientId: internal-service
      clientSecret: internal-secret
      accessTokenUri: http://adly-auth:9191/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adly
    username: adly
    password: adly
  jpa:
    hibernate:
      ddl-auto: update
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost
  cloud:
    stream:
      bindings:
        output:
          destination: beacons.exchange
          contentType: application/json
