server:
  port: ${PORT:8000}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user
    client:
      clientId: internal-service
      clientSecret: internal-secret
      accessTokenUri: http://localhost:9191/uaa/oauth/token
      grant-type: client_credentials
      scope: server
  ignored: /profile/survey/response

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adly
    username: adly
    password: adly
  jpa:
    hibernate:
      ddl-auto: update
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost
