server:
  port: ${PORT:8200}

spring:
  cloud:
      stream:
        bindings:
          input:
            destination: notifications
            group: notifications-group
            durableSubscription: true

fcm:
  endpoint: gcm.googleapis.com
  port: 5236
  sender:
    id: 42996188329
  api:
    key: AIzaSyCgHMhZMDZtJjuajw4kLu36_RgSED5GlKg
