server:
  port: ${PORT:9411}

spring:
  datasource:
    initialize: false
  sleuth:
    enabled: false

zipkin:
  store:
    type: mem

---
spring:
    profiles: docker
eureka:
    client:
        serviceUrl:
        defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/
    instance:
        prefer-ip-address: true