server:
  port: ${PORT:8000}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adly
    username: adly
    password: adly
  jpa:
    hibernate:
      ddl-auto: update
