server:
  port: ${PORT:8200}

spring:
  cloud:
      stream:
        bindings:
          input:
            destination: notifications
            group: notifications-group
            durableSubscription: true
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost

fcm:
  endpoint: gcm.googleapis.com
  port: 5236
  sender:
    id: 42996188329
  api:
    key: AIzaSyCgHMhZMDZtJjuajw4kLu36_RgSED5GlKg

