server:
  port: ${PORT:8300}


security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user
    client:
      clientId: internal-service
      clientSecret: internal-secret
      accessTokenUri: http://localhost:9191/uaa/oauth/token
      grant-type: client_credentials
      scope: server
  ignored: /device/register,/device/token

spring:
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost
  cloud:
    stream:
      bindings:
        input:
          destination: beacons.exchange
          group: beacons-device
          durableSubscription: true

