server:
  port: ${PORT:8100}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user
  ignored: /beacon/discover/**

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adly
    username: adly
    password: adly
  jpa:
    hibernate:
      ddl-auto: update
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost
  cloud:
    stream:
      bindings:
        output:
          group: beacons-group
          destination: beacons.exchange
          contentType: application/json
