server:
  port: ${PORT:8500}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adly
    username: adly
    password: adly
  jpa:
    hibernate:
      ddl-auto: update
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost
  cloud:
    stream:
      bindings:
        input:
          destination: beacons.exchange
          group: beacons-group
          durableSubscription: true

