server:
  port: ${PORT:8300}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user

spring:
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost

security:
  ignored: /device/**
