hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

server:
  port: ${PORT:8200}

fcm:
  endpoint: gcm.googleapis.com
  port: 5236
  sender:
    id: 42996188329
  api:
    key: AIzaSyCgHMhZMDZtJjuajw4kLu36_RgSED5GlKg

security:
  oauth2:
    client:
      clientId: internal-service
      clientSecret: internal-secret
      grant-type: client_credentials
      scope: server

spring:
  profiles:
    active: development

---
spring:
  profiles: development
  cloud:
      stream:
        bindings:
          input:
            destination: notifications
            group: notifications-group
            durableSubscription: true
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: localhost

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user
    client:
      accessTokenUri: http://localhost:9191/uaa/oauth/token

---
spring:
  profiles: docker
  data:
    cassandra:
      keyspace-name: adly
      port: 9042
      contact-points: ${DOCKER_IP:192.168.99.100}
  rabbitmq:
    addresses: rabbit:5672
  cloud:
    stream:
      bindings:
        input:
          destination: notifications
          group: notifications-group
          durableSubscription: true
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:9191/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:192.168.99.100}:9191/uaa/oauth/token
eureka:
   client:
      serviceUrl:
        defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/
   instance:
      prefer-ip-address: true

fcm:
  endpoint: gcm.googleapis.com
  port: 5236
  sender:
    id: 42996188329
  api:
    key: AIzaSyCgHMhZMDZtJjuajw4kLu36_RgSED5GlKg
