server:
  port: ${PORT:8200}

spring:
  cloud:
      stream:
        bindings:
          input:
            destination: notifications
            group: notifications-group
            durableSubscription: true
