server:
  port: 8080

spring:
  aop:
    proxy-target-class: true

zuul:
  ignored-services: '*'
  routes:
    adly-edge:
      path: /api/**
      serviceId: adly-edge
    adly-auth:
      path: /auth/**
      url: http://localhost:9191/uaa/

