server:
  port: 8080

zuul:
  ignored-services: '*'
  routes:
    adly-edge:
      path: /api/**
      serviceId: adly-edge
      sensitiveHeaders:
    adly-auth:
      path: /uaa/**
      stripPrefix: false
      serviceId: adly-auth
      sensitiveHeaders:

spring:
  profiles:
    active: development

---
spring:
  profiles: development
  aop:
    proxy-target-class: true

---
spring:
  profiles: docker
  aop:
    proxy-target-class: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/